
services:
  bot:
    build: .
    container_name: telegram_chat_analyzer
    restart: unless-stopped
    volumes:
      - ./file_cache:/app/file_cache
      - ./converted_chats:/app/converted_chats
      - ./raw_chats:/app/raw_chats
      - ./bot.log:/app/bot.log
    environment:
      TELEGRAM_TOKEN: <your_bot_token_here>
      OPENAI_API_KEY: <your_openai_api_key_here>
